### ISSUE TITLE
ng2-auto-complete/dist/auto-complete.component.ts - any type

### ISSUE THREAD

**Issue by kolyan131313** [jsvalley/ng2-auto-complete#2]
Hi. You are write good autocomplete. Please, could u set up type of variable
in file - ng2-auto-complete/dist/auto-complete.component.ts
on line 177 ( return function(callback: any, ms: any) )
asap if it possible, because my application cannot run without it

**Comment by allenhwkim** [comment]
Thanks for using it. can you be more specific?

**Comment by kolyan131313** [comment]
yeap, sorry for bad explanations. https://github.com/jsvalley/ng2-auto-complete/blob/master/dist/auto-complete.component.ts#L177 you are right about it. Could you set up type to `ms` param, because i have strict requirements on my project and i cant run my project without types

**Comment by allenhwkim** [comment]
You mean `ms: number`?

**Comment by kolyan131313** [comment]
yes, if it possible

**Comment by allenhwkim** [comment]
It's done.

**Comment by kolyan131313** [comment]
it's works, thanks a lot

**Comment by allenhwkim** [comment]
If this repo is useful, a star would be appreciated

**Comment by kolyan131313** [comment]
sorry, i fogot. Thanks
